global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['host.docker.internal:7002']
rule_files:
  - 'alert.rules.yml'
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093"

